Create PetEntity, AnimalDetails and pre-positioned links
Domkr4t/PetFamily pull request #2
Opened 2024-09-25 17:45 UTC by Domkr4t

BankDetails and Volunteer are not finished at this time

2024-09-25 18:12 UTC, n-cherashev requested changes

2024-09-25 18:12 UTC, n-cherashev commented on Backend/src/PetFamily.Domain/Pet.cs
> +        public AnimalDetails Breed { get; private set; } = default!;
У тебя повторяется поле с типом AnimalDetails, который содержит и тип и породу.
Либо сделай одно поле AnimalDetails, в котором будет информация о типе и породе, либо убери AnimalDetails и сделай оба поля просто string

2024-09-25 18:12 UTC, n-cherashev commented on Backend/src/PetFamily.Domain/Pet.cs
> +        public AnimalDetails Type { get; private set; } = default!;
У тебя повторяется поле с типом AnimalDetails, который содержит и тип и породу.
Либо сделай одно поле AnimalDetails, в котором будет информация о типе и породе, либо убери AnimalDetails и сделай оба поля просто string

2024-09-25 18:12 UTC, n-cherashev commented on Backend/src/PetFamily.Domain/Pet.cs
> +        public Volunteer VolunteerTelephone { get; private set; } = default!;
Тут нужно сделать класс PhoneNumber, так как у нас будет отдельная сущность Volunteer

2024-09-25 18:12 UTC, n-cherashev commented on Backend/src/PetFamily.Domain/Pet.cs
> +        public Volunteer VolunteerBankDetails { get; private set; } = default!;
Тут нужно сделать список BankDetails.

И тут нуджно убрать Volunteer, так как это будет реквизиты для перевода конкретно на помощь животному, а не волонтёру

2024-09-25 18:12 UTC, YaraOduvanchik commented on Backend/src/PetFamily.Domain/BankDetails.cs
> +        public Guid Id { get; set; }
Сделай тут ещё поля с реквизитами, а не просто ID

2024-09-25 18:12 UTC, YaraOduvanchik commented on Backend/src/PetFamily.Domain/Volunteer.cs
> +    public class Volunteer
Это убрать

2024-09-25 19:17 UTC, Domkr4t commented on Backend/src/PetFamily.Domain/Pet.cs
> +        public Volunteer VolunteerTelephone { get; private set; } = default!;
А в классе PhoneNumber, что будет содержаться?

2024-09-26 06:19 UTC, YaraOduvanchik commented on Backend/src/PetFamily.Domain/Pet.cs
> +        public Volunteer VolunteerTelephone { get; private set; } = default!;
В классе телефонного номера будет содержаться только Value и валидация.

Я написал это на будущее, так как ты уже начал использовать не примитивные типы данных, а классы

2024-09-26 06:23 UTC, YaraOduvanchik commented on Backend/src/PetFamily.Domain/PhoneNumber.cs
> +        public Guid Id { get; set; }
Тут сделай просто string Value.

В будущем PhoneNumber будет просто ValueObject, а не отдельная сущность

2024-09-26 06:32 UTC, merged