Created Volunteer and SocialNetwork, refactored AnimalDetails and BankDetails according to DDD and Result Pattern, replaced “животное” with “питомец” in Pet
Domkr4t/PetFamily pull request #3
Opened 2024-09-27 14:00 UTC by Domkr4t

2024-09-27 14:02 UTC, Domkr4t commented
Возник вопрос, нужно ли в конструкторе присваивать значение для Id, например вот так

`Id = Guid.NewGuid();`

или это будет делаться как-то по другому в дальнейшем?

2024-09-28 04:47 UTC, YaraOduvanchik requested changes

2024-09-28 04:47 UTC, YaraOduvanchik commented on Backend/src/PetFamily.Domain/Volunteer.cs
> +        public string? Patronymic { get; private set; }
Забыл ещё Email добавить

2024-09-28 04:48 UTC, YaraOduvanchik commented
> Возник вопрос, нужно ли в конструкторе присваивать значение для Id, например вот так
> 
> `Id = Guid.NewGuid();`
> 
> или это будет делаться как-то по другому в дальнейшем?

Да, нужно в конструкторе присваиать значение, делай это через параметры конструктора (Id = id)

2024-09-28 11:14 UTC, YaraOduvanchik approved these changes

2024-09-29 14:01 UTC, merged