Setup PostgreSQL Docker, configure EF Core, restructure, Entity.cs
Domkr4t/PetFamily pull request #5
Opened 2024-10-01 13:28 UTC by Domkr4t

Docker was configured to start PostgreSQL using docker-compose. A docker-compose.yml file with the configuration for starting PostgreSQL server was created.

A DbContext was created to connect to the Entity Framework Core project that uses PostgreSQL as the database. The database connection string configuration is stored in user-secrets.

Logging of database queries executed by EF Core using ILoggerFactory has been enabled.

Entity Framework Core Snakify extension was used to format column names in the database in snake_case styles.

A custom implementation of the Result class was added.

A small restructuring of the project was done.

Added base class Entity

2024-10-01 13:30 UTC, Domkr4t commented
Я не сделал миграции, потому что у меня не получилось толком сконфигурировать отношения Entity к VO, я не понял как правильно это делается.
В этом задании я случайно сделал и B-4.2 (Создание Entity.cs).

2024-10-01 15:01 UTC, KirillSachkov requested changes

2024-10-01 15:01 UTC, KirillSachkov commented on PetFamily,Backend/src/PetFamily.Infrastucture/ApplicationDbConbext.cs
> +        public DbSet<Pet> Pets => Set<Pet>();
DbSet нужно только для волонтеров, потому что мы управляем животными через волонтера, через агрегат

2024-10-01 15:01 UTC, KirillSachkov commented on PetFamily,Backend/src/PetFamily.Infrastucture/Configuration/PetConfiguration.cs
> +        }
Такая конфигурация не будет работать. тебе нужно делать обёртку над список, чтобы ты мог сконфигурировать это в jsonb столбце. Вот пример - 
![image](https://github.com/user-attachments/assets/a6a932d0-5e78-4afc-9048-d4d6b43df94e)
В 6 занятии и дальше я объясняю как такое конфигурировать, возможно даже раньше

2024-10-01 15:01 UTC, KirillSachkov commented on PetFamily,Backend/src/PetFamily.Infrastucture/Configuration/PetConfiguration.cs
> +        }
Можешь посмотреть у других ребят в репозиториях или спросить в чате, или у меня в репозитории

2024-10-08 11:59 UTC, KirillSachkov approved these changes

2024-10-08 12:58 UTC, merged